---
- hosts: all
  become: yes
  become_user: root
  vars:
    - java_version: 11
    - admin_user_pass: admin
    - jenkins_port: 8080
    - jenkins_user: cloudjournee
    - jenkins_pass: Cjptech@12
    - jenkins_fullname: CloudJournee
    - jenkins_email: nayab.s@cloudjournee.com
    - dbuser: sonarqube
    - dbpassword: sonarqube
    - dbname: sonarqube
    - sonar_admin_token: admin
    - sonar_admin_password: abhi
    - project_name: maven
    - project_key: maven
    - aws_access_key: <provide_aws_access_key>
    - aws_secret_key: <provide_aws_secret_key>
    
  tasks:
    - include_tasks: Jenkins.yml
      
